version: '3.8'
services:
  stat-db:
    image: postgres:14.5-alpine
    container_name: stat-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stat-server:
    build: ./stat
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - DB_HOST=stat-db
      - DB_PORT=5432
      - DB_NAME=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  emv-db:
    image: postgres:14.5-alpine
    container_name: emv-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=emv
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  emv-service:
    build: ./emv
    container_name: emv-service
    ports:
      - "8080:8080"
    depends_on:
      - emv-db
      - stat-server
    environment:
      - DB_HOST=emv-db
      - DB_PORT=5432
      - DB_NAME=emv
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STAT_HOST=stat-server
      - STAT_PORT=9090