CREATE TABLE IF NOT EXISTS stat
(
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app     VARCHAR(255)                         NOT NULL,
    uri     VARCHAR                              NOT NULL,
    ip      VARCHAR(28)                          NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_stat_id PRIMARY KEY (id)
);